apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: chat-app-api
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "50051"
            - name: MONGODB_URL
              value: "mongodb://root:password@mongodb-svc:27017"
          ports:
            - name: api
              containerPort: 50051
              protocol: TCP
